### ISSUE TITLE
Increased examples and documentation

### ISSUE THREAD

**Issue by spensireli** [greenbone/python-gvm#110]
When trying to automate the OpenVAS9 scanning there are many references to omp, python-gvm, gvm-cli, and gmp. Why all the variants? 

It is my understanding that omp is now deprecated, I (and I assume others) was redirected to this repo instead.  There is a wide array of documentation that exists on how to use omp and traditional cli calls. This does not exist for gvm-cli or python-gvm. The example given shows how to make connections via a UnixSocketConnection with basic get_task requests against the localhost. It appears that documentation around executing commands from a remote host does not exist. If users are being redirected to these tools and support of omp is being dropped, it would be appreciated it documentation around automating components of OpenVAS 9 was enhanced. Particularly around execution from a remote host.

**Comment by bjoernricks** [comment]
I've written an extensive documentation for [gvm-tools](https://gvm-tools.readthedocs.io/) and [python-gvm](https://python-gvm.readthedocs.io/)

> It is my understanding that omp is now deprecated, I (and I assume others) was redirected to this repo instead.

Yes I've written this statement several times at https://community.greenbone.net/
The community forum is the central place for information regarding OpenVAS/GVM. If something is unclear please do a search in the forum and open a new topic if you can't find an answer.

> it would be appreciated it documentation around automating components of OpenVAS 9 was enhanced.

Feel free to create pull requests to add additional examples and missing explanations.
