### ISSUE TITLE
Create schedule method raises an exception if the first minute or first hour is 0

### ISSUE THREAD

**Issue by Birajpjpt** [greenbone/python-gvm#111]
When creating a schedule with value 0 in either minutes or hour such as '2019-04-03T12:00:00.000Z' if we call the following method(line 1152 in gmpv7.py)

```
Gmp.create_schedule(name=schedule_name,
                                      first_time_minute=0,
                                      first_time_hour=12,
                                      first_time_day_of_month=3,
                                      first_time_month=4,
                                      first_time_year=2019,
                                      period=0,
                                      period_unit='hour',
                                      timezone='UTC'
                                       )
```

it raises an exception such as 

```
raise RequiredArgument(
                    'Setting first_time requires first_time_minute argument')
```
Few issues here:
 - Although the documentation says the first time minute, first time hour, first time moth, year and day should all be an int, they convert it to string regardless before making request to openvas to create schedule. In my current code I've fixed by sending minute and hour as string, although that is not proper way of implementing it. 

- following is appropriate way for checking if argument is not none.

```
            if first_time_minute is not None:
                raise RequiredArgument(
                    'Setting first_time requires first_time_minute argument')
```

instead of 

 ```
           if not first_time_minute:
                raise RequiredArgument(
                    'Setting first_time requires first_time_minute argument')
```

which will always be false if first_time_minute is 0 hence raises an argument

**Comment by bjoernricks** [comment]
Yes of course and it's already fixed in master see https://github.com/greenbone/python-gvm/commit/0a3d0ac069c9eb53fc12adb4b617719a58f29b84

**Comment by Birajpjpt** [comment]
Thanks @bjoernricks. Will you be releasing this any time soon?

**Comment by bjoernricks** [comment]
I do expect the final 1.0 in May.
