### ISSUE TITLE
An error occurred Remote manager daemon uses an unsupported version of GMP. The GMP version was 22.5

### ISSUE THREAD

**Issue by montjoie** [greenbone/python-gvm#1121]
With up to date python-gvm (python_gvm-24.1.0-py3-none-any.whl), I have:
An error occurred Remote manager daemon uses an unsupported version of GMP. The GMP version was 22.5
when doing
with Gmp(connection=connection, transform=transform) as gmp:
        gmp.authenticate(username, password)

The running openvas is up to date using the official docker-compose.yml

**Comment by bjoernricks** [comment]
Hi,

I am sorry but I am not able to reproduce your issue

```
mkdir -p /tmp/python-gvm-test
cd /tmp/python-gvm-test
python3 -m venv .venv
source .venv/bin/activate
python3 -m pip install python-gvm
```

```
pip list


Package      Version
------------ -------
bcrypt       4.1.2
cffi         1.16.0
cryptography 42.0.2
defusedxml   0.7.1
lxml         5.1.0
paramiko     3.4.0
pip          23.2
pycparser    2.21
PyNaCl       1.5.0
python-gvm   24.1.0
setuptools   68.1.2
```

```main.py
import sys

from gvm.connections import UnixSocketConnection
from gvm.protocols.gmp import Gmp
from gvm.transforms import EtreeTransform
from gvm.xml import pretty_print

connection = UnixSocketConnection(path=sys.argv[1])
transform = EtreeTransform()

with Gmp(connection, transform=transform) as gmp:
    # Retrieve GMP version supported by the remote daemon
    version = gmp.get_version()

    # Prints the XML in beautiful form
    pretty_print(version)
```

```
python3 main.py /path/to/gvmd.sock
```
```xml
<get_version_response status="200" status_text="OK">
  <version>22.5</version>
</get_version_response>
```

If GMP 22.5 isn't supported the same error message would have been raised. `Remote manager daemon uses an unsupported version of GMP. The GMP version was 22.5.` See https://github.com/greenbone/python-gvm/blob/main/gvm/protocols/gmp.py#L95-L101 for the code.

**Comment by montjoie** [comment]
If I understand correctly the code, the error is that the remote is 22.5

**Comment by bjoernricks** [comment]
The error is, the remote GMP version of gvmd is at 22.5 and your imported python-gvm version doesn't support 22.5.

**But** the current release of python-gvm (24.1.0) supports GMP 22.5 as my code example shows. Thus I suspect your python environment doesn't contain the latest release of python-gvm.

**Comment by bjoernricks** [comment]
To print the version of python-gvm in your current environment you can use the following snippet.
```
python3 -c "import gvm;print(gvm.get_version())"
```

**Comment by montjoie** [comment]
I found why, a docker volume was masking the install directory. Sorry

**Comment by YgorAlberto** [comment]
I am with the same error here:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gvmtools/script.py", line 87, in main
    with protocol_class(connection, transform=transform) as protocol:
  File "/usr/lib/python3/dist-packages/gvm/protocols/gmp.py", line 119, in __enter__
    self._gmp = self.determine_supported_gmp()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gvm/protocols/gmp.py", line 111, in determine_supported_gmp
    raise GvmError(
gvm.errors.GvmError: Remote manager daemon uses an unsupported version of GMP. The GMP version was 22.5

My GVM are up-to-date (GVM-23.11.0) and my python-gvm are 24.3.0
Still getting this error :(

**Comment by bjoernricks** [comment]
If you have python-gvm >= 23.12.0 installed in the correct Python environment you have support for GMP 22.5

https://github.com/greenbone/python-gvm/releases/tag/v23.12.0
https://github.com/greenbone/python-gvm/pull/1097
https://github.com/greenbone/python-gvm/blob/main/gvm/protocols/gmp.py#L95-L96

**Comment by YgorAlberto** [comment]
Thanks for the reply
So how do I see if my python-gvm are installed in the correct python environment?

I updated it for version 24.3.0 latest on, using normal user and root user, both are showing that my python-gvm are 24.3.0
I'll see those links you sent. Thanks
