### ISSUE TITLE
Error on calling get_report function

### ISSUE THREAD

**Issue by emahdij** [greenbone/python-gvm#121]
When I call `get_report` function with XML `report_format_id` I got this error:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/gvm/connections.py", line 71, in _feed_xml
    self._parser.feed(data)
  File "src/lxml/parser.pxi", line 1242, in lxml.etree._FeedParser.feed
  File "src/lxml/parser.pxi", line 1364, in lxml.etree._FeedParser.feed
  File "src/lxml/parser.pxi", line 592, in lxml.etree._ParserContext._handleParseResult
  File "src/lxml/parser.pxi", line 601, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 711, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 640, in lxml.etree._raiseParseError
  File "<string>", line 1
lxml.etree.XMLSyntaxError: XML declaration allowed only at the start of the document, line 1, column 578

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mehdi/PycharmProjects/openvas/Main2.py", line 53, in <module>
    print(gmp.get_report(report_id=report_id,report_format_id=xml))
  File "/usr/local/lib/python3.6/dist-packages/gvm/protocols/gmpv7.py", line 3445, in get_report
    return self._send_xml_command(cmd)
  File "/usr/local/lib/python3.6/dist-packages/gvm/protocols/base.py", line 78, in _send_xml_command
    return self.send_command(xmlcmd.to_string())
  File "/usr/local/lib/python3.6/dist-packages/gvm/protocols/base.py", line 133, in send_command
    raise e
  File "/usr/local/lib/python3.6/dist-packages/gvm/protocols/base.py", line 130, in send_command
    response = self._read()
  File "/usr/local/lib/python3.6/dist-packages/gvm/protocols/base.py", line 55, in _read
    return self._connection.read()
  File "/usr/local/lib/python3.6/dist-packages/gvm/connections.py", line 135, in read
    self._feed_xml(data)
  File "/usr/local/lib/python3.6/dist-packages/gvm/connections.py", line 76, in _feed_xml
    e,
gvm.errors.GvmError: ('Cannot parse XML response. Response data read b\'<get_reports_response status="200" status_text="OK"><report type="scan" id="5bf1505e-e4fd-4f72-babd-2d4e1955ce03" format_id="5057e5cc-b825-11e4-9d0e-28d24461215b" extension="xml" content_type="text/xml"><owner><name>admin</name></owner><name>2019-05-02T08:07:41Z</name><comment></comment><creation_time>2019-05-02T08:07:41Z</creation_time><modification_time></modification_time><writable>0</writable><in_use>0</in_use><task id="2180d963-d4a4-4f6f-aa68-90a1e39f6899"></task><report_format id="5057e5cc-b825-11e4-9d0e-28d24461215b"><name>Anonymous XML</name></report_format><?xml version="1.0" encoding="UTF-8"?>\\n<report id="5bf1505e-e4fd-4f72-babd-2d4e1955ce03">\\n  <omp>\\n    <version>7.0</version>\\n  </omp>\\n  <sort>\\n    <field>type<order>ascending</order></field>\\n  </sort>\\n  <filters id="">\\n    <term>apply_overrides=0 min_qod=70 first=1 rows=1000 sort=name</term>\\n    <filter>High</filter>\\n    <filter>Medium</filter>\\n    <filter>Low</filter>\\n    <filter>Log</filter>\\n    <filter>Debug</filter>\\n    <keywords>\\n      <keywor\'', XMLSyntaxError('XML declaration allowed only at the start of the document, line 1, column 578',))
```
And this is my code:
```python
x = gvm.connections.TLSConnection(hostname='192.168.29.138')
gmp = Gmp(connection=x)
username = 'admin'
password = '123'
gmp.authenticate(username=username, password=password)
xml='5057e5cc-b825-11e4-9d0e-28d24461215b'
print(gmp.get_report(report_id=report_id,report_format_id=xml))
```

### GVM versions
**gsa:** (gsad --version)
Greenbone Security Assistant 7.0.3

**gvm:** (gvmd --version)
-bash: gvmd: command not found

**openvas-scanner:** (openvassd --version)
OpenVAS Scanner 5.1.3

**gvm-libs:**

mport gvm
from gvm.connections import UnixSocketConnection, DebugConnection
from gvm.protocols.latest import Gmp

**gvm-tools:** (gvm-cli --version)
gvm-cli 2.0.0.beta1. API version 1.0.0.beta2

### Environment
**Operating system:**
kalli linux
**Installation method / source:** (packages, source installation)
apt-get install openvas

**Comment by M1dor1ya** [comment]
I have the same problem as you. It seems that when parsing an XML document, bytes are parsed directly instead of string.

**Comment by bjoernricks** [comment]
This issue is cause by including an xml document within the xml based response. The parser doesn't allow this currently. IMHO is is an issue in the backend. Would you be able to test this with a newer version?

**Comment by M1dor1ya** [comment]
I just used the latest version for testing(1.0.0b3.dev1),but the problem still seems to exist. My testing method is to request get_tasks API at a faster speed, and the following problems will arise:
![image](https://user-images.githubusercontent.com/30382550/62855082-cd74ce00-bd23-11e9-946b-ca220e8500ef.png)
If you request API at a slower rate, you won't encounter this problem.

**Comment by bjoernricks** [comment]
@M1dor1ya Not sure what's happening at your side but is is of course a different issue as described in this ticket. With

>Would you be able to test this with a newer version?

I meant a newer version of the backend.

**Comment by M1dor1ya** [comment]
I'm sorry I misunderstood what you meant.It seems that the GMP object returns the bytes type instead of str in some case. The following is my code,thanks for your help.
![image](https://user-images.githubusercontent.com/30382550/62856290-14b08e00-bd27-11e9-9c0f-c5da29e5eae5.png)

**Comment by M1dor1ya** [comment]
I've solved this problem, and using Django develop servers can cause this problem. I'm not sure why, but it's not really an XML parsing problem.

**Comment by bjoernricks** [comment]
All commands using a single connection must be run in sequence. It is not possible to share a connection.

**Comment by bjoernricks** [comment]
For anon xml export this is fixed with https://github.com/greenbone/gvmd/pull/965

**Comment by y0urself** [comment]
As this issue is really outdated. I will close it for now. If any related bugs occur please create a new issue.
