### ISSUE TITLE
python-gvm not compatible with latest GMPv8 changes

### ISSUE THREAD

**Issue by gpapakyriakopoulos** [greenbone/python-gvm#122]
It seems the python-gvm library has not incorporated properly the changes made to the GMP protocol with the release of version 8.0 as described here : https://docs.greenbone.net/API/GMP/gmp-8.0.html#changes

More specifically, the change to the "create_target" command has not been implemented properly. As per the resource linked above, GMPv8 has removed the "MAKE_UNIQUE" name from the expected request/response bodies. When trying to call the "create_target" command via python-gvm against a GMPv8 scanning instance, I am presented with the following error :

GvmError: ('Error in response. Bogus element: make_unique')

A call to the scanning instance for its GMP version returns the following :

<get_version_response status="200" status_text="OK"><version>8.0</version></get_version_response>

It appears that although "MAKE_UNIQUE" was removed from the request validation, it is still returned as part of the response body and therefore fails validation in python-gvm

**Comment by gpapakyriakopoulos** [comment]
It seems that happens only if you keep passing the make_unique argument to the "create_target" command

**Comment by bjoernricks** [comment]
Currently python-gvm doesn't support GMP 8 completely. There is a first draft in gvm.protocols.gmpv8 but it isn't official yet and will change until the next release.
