### ISSUE TITLE
Error on calling create_target function with alive_test set

### ISSUE THREAD

**Issue by carlstegmann** [greenbone/python-gvm#147]
### Expected behavior
Target is created using the desired alive option.

### Current behavior
An error is reported from gvm.errors.InvalidArgument: Invalid argument alive_test for create_target

### Steps to reproduce
1. call gmp.create_target with alive_test set.

### GVM versions
**gsad:** Greenbone Security Assistant 8.0.0~git

**gvm:** Greenbone Vulnerability Manager 8.0.0

**openvas-scanner:** OpenVAS Scanner 6.0.0

**gvm-libs:** gvm-libs-10.0.0

**gvm-tools:** python-gvm 1.0.0b3

### Environment
**Operating system:** Ubuntu 18.04

**Installation method / source:** source installation

### Fix

The bug exists, because alive_test is a string.
This bug can be fixed by calling "get_alive_test_from_string(alive_test)".

```
diff --git a/gvm/protocols/gmpv7/__init__.py b/gvm/protocols/gmpv7/__init__.py
index 09ae5f0..0c5fbf5 100644
--- a/gvm/protocols/gmpv7/__init__.py
+++ b/gvm/protocols/gmpv7/__init__.py
@@ -1769,6 +1769,7 @@ class Gmp(GvmProtocol):
             cmd.add_element("snmp_credential", attrs={"id": snmp_credential_id})

         if alive_test:
+            alive_test = get_alive_test_from_string(alive_test)
             if not isinstance(alive_test, AliveTest):
                 raise InvalidArgument(
                     function="create_target", argument="alive_test"
```

**Comment by bjoernricks** [comment]
alive_test needs to be an [AliveTest](https://python-gvm.readthedocs.io/en/latest/api/gmpv7.html#gvm.protocols.gmpv7.AliveTest) enum instance. All types arguments have to be an enum class instance with beta 3 now.
