### ISSUE TITLE
Installation instructions not python3 related

### ISSUE THREAD

**Issue by dh3wr** [greenbone/python-gvm#160]
### Expected behavior
https://pypi.org/project/python-gvm/#Install-using-pip
Given command should work.
Correct command: ``pip3 install --user python-gvm``

### Current behavior
````
root@openvas:~# pip install --user python-gvm
Collecting python-gvm
  Could not find a version that satisfies the requirement python-gvm (from versions: )
No matching distribution found for python-gvm
````
### Steps to reproduce
1. Try to install python-gvm accroding to the instructiuons

### GVM versions
**gsa:** (gsad --version)
Not important
**gvm:** (gvmd --version)
Not important
**openvas-scanner:** (openvassd --version)
Not important
**gvm-libs:**
Not important
**gvm-tools:** (gvm-cli --version)
Not important
### Environment
**Operating system:**
Ubuntu 18.04
**Installation method / source:** (packages, source installation)
https://pypi.org/project/python-gvm/#Install-using-pip
### Logfiles

```

```

**Comment by dh3wr** [comment]
Same here ``https://python-gvm.readthedocs.io/en/latest/install.html#using-pip``

**Comment by bjoernricks** [comment]
python-gvm (as gvm-tools) is Python 3 only. Therefore I've you use the pip version provided by your distribution you need to use pip3. #161 updates the docs accordingly.
