### ISSUE TITLE
[1.4.0] rpm packaging impossible, because of missing setup.py

### ISSUE THREAD

**Issue by tuxmaster5000** [greenbone/python-gvm#201]
On 1.4.0 the setup.py file was removed.
But the build for rpm packages relay on it.
And no hint is in the release notes how to generate now setup.py.

**Comment by bjoernricks** [comment]
The setup.py file isn't necessary for building and installing distributable python packages anymore. See [PEP 517](https://www.python.org/dev/peps/pep-0517/) and [PEP 518](https://www.python.org/dev/peps/pep-0518/). We completely switched to [poetry](https://github.com/python-poetry/poetry) which replaces pipenv, setuptools and also twine.

**Comment by bjoernricks** [comment]
Just found out that the source distribution still contains a `setup.py` file.
`poetry build --format=dist` which is run with `poetry build` too will generate a setup.py in the created source distribution.

**Comment by tuxmaster5000** [comment]
I have try it, but it fails with:
poetry build --format=dist
Creating virtualenv python-gvm in /builddir/build/BUILD/python-gvm-1.4.0/.venv
Building python-gvm (1.4.0)

[ValueError]
Invalid format: dist

**Comment by tuxmaster5000** [comment]
Only sdist looks valid, but this fails with:
```
poetry build --format=sdist
Creating virtualenv python-gvm in /builddir/build/BUILD/python-gvm-1.4.0/.venv
Building python-gvm (1.4.0)
 - Building sdist
 - Built python-gvm-1.4.0.tar.gz
+ CFLAGS='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic'
+ LDFLAGS='-Wl,-z,relro '
+ /usr/bin/python3 setup.py build '--executable=/usr/bin/python3 -s'
/usr/bin/python3: can't open file 'setup.py': [Errno 2] No such file or directory

```

**Comment by tuxmaster5000** [comment]
It looks like poetry can't do that.
https://github.com/python-poetry/poetry/issues/761

**Comment by bjoernricks** [comment]
Not sure why it doesn't work for you. Maybe lxml need to be build and that fails for you with poetry.

```bash
> poetry --version           
Poetry version 1.0.5
```
```bash
> poetry build --format=sdist   
Building python-gvm (1.4.0)
 - Building sdist
 - Built python-gvm-1.4.0.tar.gz
```
`poetry build` also runs just fine on our CI instances.

**Comment by bjoernricks** [comment]
IMHO installing python-gvm via pip from a git url or using the editable mode may not work without the setup.py file because this behavior isn't specified (yet). But building sdists and wheels should be possible because that's what [PEP 517](https://pypi.org/project/pep517/) is about.

**Comment by tuxmaster5000** [comment]
Sorry my mistake. :(
poetry build creates an tar archive and not only the file. This was the point.
```
poetry build --format=sdist
tar xzf dist/%{pypi_name}-%{version}.tar.gz
cp -rf %{pypi_name}-%{version}/* .
rm -rf dist .venv %{pypi_name}-%{version} 
```
Was the trick. Now the default way of packaging under the RedHat world will work.
Thanks for your help.

**Comment by bjoernricks** [comment]
Alternatively you can use the source distribution from pypi https://pypi.org/project/python-gvm/#files 

Direct link: https://files.pythonhosted.org/packages/6e/81/3c7dc7d2a840bc816e0c673fd99f37265662558f6d95ec7dc0db953074b4/python-gvm-1.4.0.tar.gz

**Comment by tuxmaster5000** [comment]
Yes of course, this will be the second option.
