### ISSUE TITLE
Why modify_ config_ set_ nvt_ The preference interface is not valid？

### ISSUE THREAD

**Issue by zty1304368100** [greenbone/python-gvm#344]
i want update Openvas Scan Configs NVT Preferences,I called this API "modify_config_set_nvt_preference", but is not effective,who can tell me why ? Thanks !
here is my code:
```
with Gmp(connection, transform=transform) as gmp:
    gmp.authenticate('admin', 'admin')
    resu = gmp.modify_config_set_nvt_preference("uuid",name="CGI Scanning Consolidation",nvt_oid="oid1", value='90')
    pretty_print(resu)
```

**Comment by y0urself** [comment]
What is the actual response?

**Comment by zty1304368100** [comment]
> What is the actual response?

<modify_config_response status="200" status_text="OK"/>
