### ISSUE TITLE
gvm-cli socket connections quiet and time out!

### ISSUE THREAD

**Issue by asmaack** [greenbone/python-gvm#48]
Not sure if this issue belongs here, but I suspect python-gvm/gvm/connections.py to be the cause of this.

I just upgraded python-gvm and gvm-tools today. After the upgrade, many gvm-cli socket commands will hang and timeout with "Connection was closed by remote server". No other errors are thrown and openvasmd log is empty. Looks like these commands do not reach openvasmd.

openvasmd, openvassd and gsad are however working correctly.

To reproduce, some examples:

```
$ gvm-cli socket -c --xml "<get_version>"
Connection was closed by remote server

$ gvm-cli socket -c --xml "<get_port_lists>"
Connection was closed by remote server

$ gvm-cli socket -c --xml "<get_configs>"
Connection was closed by remote server

gvm-cli socket -c --xml "<get_scanners>"
Connection was closed by remote server

$ openvasmd --get-scanners
08b69003-5fc2-4037-a479-93b440211c73  OpenVAS Default
6acd0832-df90-11e4-b9d5-28d24461215b  CVE

$ gvm-cli socket -c --xml "<get_users>"
Connection was closed by remote server

$ openvasmd --get-users
admin
```

Some commands however will work correctly:

```
$ gvm-cli socket -c --xml "<get_nvts family=\"IT-Grundschutz-12\" details=\"1\"/>"
<get_nvts_response status="200" status_text="OK">...</get_nvts_response>

$ gvm-cli socket -c --xml "<get_xxx>"
('Error in response. Bogus command name', <Element omp_response at 0x7f09f6462488>)
```

### GVM versions
**gsa:** (gsad --version)
Greenbone Security Assistant 7.0.4
GIT revision 8bc4902b7-gsa-7.0

**openvasmd:** (openvasmd --version)
OpenVAS Manager 7.0.4
GIT revision a8d29fc4-openvas-manager-7.0
Manager DB revision 184

**openvas-scanner:** (openvassd --version)
OpenVAS Scanner 5.1.3

**gvm-libs:** (git log)
commit 745eee685f57ee56292f53c31137b92b5e84c7e7 (HEAD -> openvas-libraries-9.0, origin/openvas-libraries-9.0)

**gvm-tools:** (gvm-cli --version)
gvm-cli 2.0.0.beta1. API version 1.0.0.dev1

**gvm-tools:** (git log)
commit e9dabe9ba46f0cc929c5f63bf42d52a50961a8ac (HEAD -> master, origin/master, origin/HEAD)

**python-gvm:** (git log)
commit 0953fa29e88ef0c280c06e59d1dab7eaf804c22f (HEAD -> master, origin/master, origin/HEAD)

### Environment
**Operating system:**
$ uname -a
Linux xxx 4.15.0-38-generic #41-Ubuntu SMP Wed Oct 10 10:59:38 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Installation method / source:** (packages, source installation)
sudo -H pip3 install .

**Comment by bjoernricks** [comment]
Easy solution. Your request must be valid xml.

> $ gvm-cli socket -c --xml "<get_version>"
> $ gvm-cli socket -c --xml "<get_port_lists>"
> $ gvm-cli socket -c --xml "<get_configs>"
> gvm-cli socket -c --xml "<get_scanners>"
> $ gvm-cli socket -c --xml "<get_users>"

All these commands are missing the closing tag. Therefore gvmd is still waiting for your request to end. Just use e.g. `<get_version/>'

**Comment by asmaack** [comment]
Quick fingers. So true!
Thanks.
