### ISSUE TITLE
Wrong report format

### ISSUE THREAD

**Issue by vulnz** [greenbone/python-gvm#669]
Good day.
Export of CSV gives XSLX format.
Please check it out and let me know if possible on how to export CSV format, same as we export from panel.
thanks

**Comment by bjoernricks** [comment]
Without full details what you have done it is nearly impossible to debug your specific issue. Please provide us some code to reproduce the behavior.

**Comment by vulnz** [comment]
![image](https://user-images.githubusercontent.com/20043135/152110594-1a848be8-2fb5-438b-929b-0a5c06d360b5.png)
Report format for CVS != CSV, it is XLSX in base64.
Thanks

**Comment by bjoernricks** [comment]
Could you give me some code where you are using the API to get what's wrong here. It's not obvious from your screenshot.

Just as a side note the reports are always encoded as base64 to be embedded in the XML. See for example the pdf export example as a GMP script at https://github.com/greenbone/gvm-tools/blob/main/scripts/export-pdf-report.gmp.py#L80

**Comment by vulnz** [comment]
`    report2 = gmp.get_report_formats()
    pretty_print(report2)
    report=gmp.get_report(report_id='xxx-xxx-xxx', report_format_id='c1645568-627a-11e3-a660-406186ea4fc5')
    abc=pretty_print (report)
`
After I extract base64 to file and it is XLSX, not CSV as expected. BTW it sill be good to add example on how to call this functions as well, had to read github repo source code to understand this.
How to get CSV? 
thanks

**Comment by bjoernricks** [comment]
We don't have a report format that creates XLS or XLSX. The Report Format with UUID `c1645568-627a-11e3-a660-406186ea4fc5` creates a CSV file using comma as separator. 

How did you notice that it is a XLSX file? Could you try running the `file` command on the generated report?

**Comment by vulnz** [comment]
You are right, my friend.
