### ISSUE TITLE
Enum field ALLINFO for InfoType is missing

### ISSUE THREAD

**Issue by ikreb7** [greenbone/python-gvm#699]
### Expected behavior

The function [get_info_list](https://python-gvm.readthedocs.io/en/latest/api/gmpv214.html#gvm.protocols.gmpv214.Gmp.get_info_list) mentions ``ALLINFO``. But the enum [InfoType](https://python-gvm.readthedocs.io/en/latest/api/gmpv214.html#gvm.protocols.gmpv214.InfoType) doesn't know ``ALLINFO``.

### Current behavior

    ValueError: 'ALLINFO' is not a valid InfoType

### Steps to reproduce

    pretty_print(gmp.get_info_list(InfoType("ALLINFO"))

### GVM versions
**gsa:** (gsad --version)
Greenbone Security Assistant 21.4.3

**gvm:** (gvmd --version)
Greenbone Vulnerability Manager 21.4.4

### Environment
**Operating system:** ubuntu-20.04

**Installation method / source:** (packages, source installation)

python-gvm==21.11.0 with pip

**Comment by bjoernricks** [comment]
ALLINFO has been removed with the 20.08 release. Therefore only the docs where not up to date. There is not `InfoType.ALLINFO` anymore.
