### ISSUE TITLE
How can I change the user-agent and set a proxy for scans?

### ISSUE THREAD

**Issue by everping** [greenbone/python-gvm#813]
As title, I'd like to change the default User-agent which contains `OpenVAS-VT` to another value

I also want my scans to run through an HTTP Proxy, is this possible?

**Comment by bjoernricks** [comment]
Hi,

this is a question regarding VTs rather then an issue with python-gvm. Therefore I am closing this ticket. Feel free to ask at https://community.greenbone.net/ instead.

**Comment by everping** [comment]
@bjoernricks As I understand, it's not a question regarding VTs. 

I'm looking for methods to change user-agent and proxy but didn't find them in the python-gvm source code. That's why I asked here

**Comment by bjoernricks** [comment]
I suppose you are asking about the user agent during a scan. Scans are run by openvas-scanner and executing Vulnerability Tests (VTs). These VTs have a user agent set. You request is still a question on howto do something and not reporting an issue with python-gvm. Therefore you should better ask at https://community.greenbone.net/

**Comment by everping** [comment]
@bjoernricks in an attempt to find the answer myself, I rechecked `python-gvm` and found a method that can change the `user-agent`. But I believe it didn't work, specifically `get_scan_config_preference` and `modify_scan_config_set_nvt_preference`

I put my script here and hope you can take a look at this

```python
import json
import xmltodict
from xml.etree import ElementTree
from gvm.protocols.gmp import Gmp
from gvm.transforms import EtreeCheckCommandTransform
from gvm.connections import TLSConnection

CONFIG_NAME = 'Full and fast'
NVT_OID = '1.3.6.1.4.1.25623.1.0.12288'


def xml_to_json(xml_object):
    json_object = ElementTree.tostring(xml_object)
    json_object = xmltodict.parse(json_object)
    return json.loads(json.dumps(json_object))


connection = TLSConnection(hostname='xxxxx', port=9390)
transform = EtreeCheckCommandTransform()
with Gmp(connection, transform=transform) as gmp:
    gmp.authenticate('xxxxx', 'xxxxx')
    scan_configs = xml_to_json(gmp.get_scan_configs())['get_configs_response']['config']
    for cfg in scan_configs:
        if cfg.get('name') == CONFIG_NAME:
            config_id = cfg.get('@id')
            clone_scan_config = gmp.clone_scan_config(config_id=config_id)
            clone_scan_config_id = xml_to_json(clone_scan_config)['create_config_response']['@id']
            
            # I can get all preferences here
            x = gmp.get_scan_config_preferences(config_id=clone_scan_config_id,
                                                nvt_oid=NVT_OID)
            print(xml_to_json(x)['get_preferences_response']['preference'])
            
            # But I cannot get a preference by its name 
            x = gmp.get_scan_config_preference(config_id=clone_scan_config_id,
                                               name='HTTP User-Agent',
                                               nvt_oid=NVT_OID)
            print(xml_to_json(x))
            
            # The modify method also does not work
            x = gmp.modify_scan_config_set_nvt_preference(config_id=clone_scan_config_id,
                                                          name='HTTP User-Agent',
                                                          value='new user agent',
                                                          nvt_oid=NVT_OID)
            print(xml_to_json(x))
            
            # I get all preferences again to see that the user agent remains unchanged
            x = gmp.get_scan_config_preferences(config_id=clone_scan_config_id,
                                                nvt_oid=NVT_OID)
            print(xml_to_json(x)['get_preferences_response']['preference'])

```

**Comment by y0urself** [comment]
In order to correctly modify your scan config nvt preference you need to use a more complex string.
You need to use this string for the `name` value:
```
# {NVT-OID}:{preference-id}:{datatype}:{name}
# e.g.:
nvt_oid="1.3.6.1.4.1.25623.1.0.108652" name="1.3.6.1.4.1.25623.1.0.108652:2:checkbox:Use only AE Titles in uploaded file"
```

**Comment by everping** [comment]
@y0urself Thanks for your very helpful answer. Before I captured the request from Web UI to change NVT preferences and realized the name format as you mentioned. The `modify_scan_config_set_nvt_preference` works now.

However, the `get_scan_config_preference` still returns `{'get_preferences_response': {'@status': '200', '@status_text': 'OK'}}` which is no meaning for users

**Comment by everping** [comment]
Btw, do you know any method that can help me to change the HTTP Proxy?
