### ISSUE TITLE
Is all get_ commands supposed to return a string instead of xml?

### ISSUE THREAD

**Issue by falkowich** [greenbone/python-gvm#9]
In the example in the README.md is seems like these get_ functions should return an xml object.
```
# Retrieve all tasks
tasks = gmp.get_tasks()

# Get names of tasks
task_names = tasks.xpath('task/name/text()')
```
But now they seem to return an string
Is this an error or by design?
```
   def get_tasks_command(self, kwargs):
        """Generates xml string for get tasks on gvmd."""
        cmd = XmlCommand('get_tasks')
        cmd.set_attributes(kwargs)
        return cmd.to_string()
```
--
Regards Falk

**Comment by bjoernricks** [comment]
First of all GmpCommandFactory is not a public api and will be removed in future. My plan is to remove it before the final python-gvm 1.0 release. And it only creates gmp xml commands as a string.

Second I did change the Gmp class to allow to return any kind of python type from each get/modify/delete/.. method.
Please take a look at the [`gvm.protocols.gmpv7.Gmp __init__` method](https://github.com/greenbone/python-gvm/blob/master/gvm/protocols/gmpv7.py#L85) for the transform parameter and [`gvm.transforms`](https://github.com/greenbone/python-gvm/blob/master/gvm/transforms.py) for the build in classes for this parameter. Passing a transform allows to change the response.

But you are right. The example in the README.md is currently wrong. By default the Gmp methods are returning a string. A [EtreeTransform](https://github.com/greenbone/python-gvm/blob/master/gvm/transforms.py#L26) instance should be passed to Gmp as transform param.
